# Set folder to clover (must be the same on travis)
coverage_clover: tests/_output/clover.xml
# Same folder here
json_path: tests/_output/coveralls-upload.json
# Don't touch that
service_name: travis-ci