name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1']
        codeception: ['4.1', '5.0']

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: |
        composer require "codeception/codeception:^${{ matrix.codeception }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: php-${{ matrix.php }}-codeception-${{ matrix.codeception }}
        COVERALLS_PARALLEL: true
      run: composer check

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
